### PR TITLE
Added weekly schedule markdown

### PR DESCRIPTION
**Pull request by d-herz**
Hey! 
I placed the schedule markdown near the top, but feel free to move it down further if that works better! 

I imagine the schedule to be a sort of 'living' document that we change and update as we move through each week. For now (at least to start) I added the recurring events that we are aware of and included the holiday for this week. 

Hopefully, others will help us keep track of events and things happening so we can be sure to add them.

### CODE REVIEW

**Comment by Michael-Futral** [comment]
Looks perfect!! Will pull in and should be live now!

**Comment by d-herz** [comment]
Awesome!

**Comment by Michael-Futral** [comment]
Added you as one of the maintainers for this readme repo so you should be able to make changes as needed to it.

**Comment by d-herz** [comment]
Ok perfect that will make it easy to make changes on the fly throughout the week when necessary

**Pull request merged**
